<?xml version = '1.0' encoding = 'UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://TargetNamespace.com/Inn_Servicios_Sel_Suscriptor_PostaddNewSuscriptor_request" targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_Suscriptor_PostaddNewSuscriptor_request" elementFormDefault="qualified" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" nxsd:version="JSON" nxsd:encoding="UTF-8">
   <xsd:element name="Root-Element">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="sucursal" type="xsd:integer"/>
            <xsd:element name="suscriptor" type="xsd:integer"/>
            <xsd:element name="nombre_completo" type="xsd:string"/>
            <xsd:element name="exterior" type="xsd:integer"/>
            <xsd:element name="tipo_registro" type="xsd:string"/>
            <xsd:element name="registro" type="xsd:string"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
<xsd:annotation xmlns="">
      <xsd:appinfo>NXSDSAMPLE=</xsd:appinfo>
      <xsd:appinfo>USEHEADER=false</xsd:appinfo>
   </xsd:annotation>
</xsd:schema>