<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
            xmlns="http://TargetNamespace.com/Inn_Servicios_Sel_EdoCuenta_GetDataEstadoCuenta_response"
            targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_EdoCuenta_GetDataEstadoCuenta_response"
            nxsd:version="JSON"
            nxsd:encoding="UTF-8"
            elementFormDefault="qualified">

  <xsd:element name="Root-Element">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="datos_generales">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="codigoBarras" type="xsd:string"/>
              <xsd:element name="nombre" type="xsd:string"/>
              <xsd:element name="apellidoPaterno" type="xsd:string"/>
              <xsd:element name="apellidoMaterno" type="xsd:string"/>
              <xsd:element name="lineaScotiabank" type="xsd:string"/>
              <xsd:element name="lineaSantander" type="xsd:string"/>
              <xsd:element name="lineaBital" type="xsd:string"/>
              <xsd:element name="lineaBancomer" type="xsd:string"/>
              <xsd:element name="lineaBanamex" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:annotation xmlns=""><xsd:appinfo>NXSDSAMPLE=</xsd:appinfo><xsd:appinfo>USEHEADER=false</xsd:appinfo></xsd:annotation>
</xsd:schema>