<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
            xmlns="http://TargetNamespace.com/Inn_Servicios_Sel_Recargas_GetPaquetesRecarga_response"
            targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_Recargas_GetPaquetesRecarga_response"
            nxsd:version="JSON"
            nxsd:encoding="UTF-8"
            elementFormDefault="qualified">

  <xsd:element name="Root-Element">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="recargar" type="xsd:string"/>
        <xsd:element name="mensaje" type="xsd:string"/>
        <xsd:element name="numero" type="xsd:string"/>
        <xsd:element name="tipo_recarga" type="xsd:string"/>
        <xsd:element name="paquetes" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Id_paquete" type="xsd:string"/>
              <xsd:element name="monto" type="xsd:string"/>
              <xsd:element name="vigencia" type="xsd:string"/>
              <xsd:element name="datos" type="xsd:string"/>
              <xsd:element name="minutos" type="xsd:string"/>
              <xsd:element name="sms" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:annotation xmlns=""><xsd:appinfo>NXSDSAMPLE=</xsd:appinfo><xsd:appinfo>USEHEADER=false</xsd:appinfo></xsd:annotation>
</xsd:schema>