<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
            xmlns="http://TargetNamespace.com/Inn_Servicios_Sel_Diagnostico_PostActivateRedWifi_request"
            targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_Diagnostico_PostActivateRedWifi_request"
            nxsd:version="JSON"
            nxsd:encoding="UTF-8"
            elementFormDefault="qualified">
  <xsd:element name="Root-Element">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="sucursal" type="xsd:string"/>
        <xsd:element name="suscriptor" type="xsd:string"/>
        <xsd:element name="origen" type="xsd:string"/>
        <xsd:element name="data" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Tipo_Wifi" type="xsd:string"/>
                    <xsd:element name="Id_suscriptor" type="xsd:string"/>
                    <xsd:element name="Id_sistema" type="xsd:string"/>
                    <xsd:element name="Parametros" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="nombre" type="xsd:string"/>
                          <xsd:element name="valor" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:annotation xmlns=""><xsd:appinfo>NXSDSAMPLE=</xsd:appinfo><xsd:appinfo>USEHEADER=false</xsd:appinfo></xsd:annotation>
</xsd:schema>