<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
           xmlns:tns="http://TargetNamespace.com/Inn_Servicios_Sel_Servicios_GetListaServiciosContratados_response"
           targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_Servicios_GetListaServiciosContratados_response"
           elementFormDefault="qualified" attributeFormDefault="unqualified"
           nxsd:version="JSON" nxsd:jsonTopLevelArray="true" nxsd:encoding="UTF-8">
  <xs:element name="Root-Element">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="topLevelArray" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="idcontrato" type="xs:string"/>
              <xs:element name="estado" type="xs:string"/>
              <xs:element name="destiposervicio" type="xs:string"/>
              <xs:element name="desservicio" type="xs:string"/>
              <xs:element name="desequipo" type="xs:string"/>
              <xs:element name="tipocontrato" type="xs:string"/>
              <xs:element name="fechacontratacion" type="xs:string"/>
              <xs:element name="fechainstalacion" type="xs:string"/>
              <xs:element name="fechacancelacion" type="xs:string"/>
              <xs:element name="fechacorte" type="xs:string"/>
              <xs:element name="fechareactivacion" type="xs:string"/>
              <xs:element name="fechareconexion" type="xs:string"/>
              <xs:element name="fechasuspension" type="xs:string"/>
              <xs:element name="fechaultimocargo" type="xs:string"/>
              <xs:element name="fechaultimopago" type="xs:string"/>
              <xs:element name="modelo" type="xs:string"/>
              <xs:element name="serie" type="xs:string"/>
              <xs:element name="servicio" type="xs:string"/>
              <xs:element name="tiposervicio" type="xs:string"/>
              <xs:element name="tipoequipo" type="xs:string"/>
              <xs:element name="vendido" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>