<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
            xmlns="http://TargetNamespace.com/Inn_Servicios_Sel_EdoCuenta_SendSmsEdocta_response"
            targetNamespace="http://TargetNamespace.com/Inn_Servicios_Sel_EdoCuenta_SendSmsEdocta_response"
            nxsd:version="JSON"
            nxsd:encoding="UTF-8"
            elementFormDefault="qualified">

  <xsd:element name="Root-Element">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="respuesta" type="xsd:string"/>
        <xsd:element name="mensaje" type="xsd:string"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:annotation xmlns=""><xsd:appinfo>NXSDSAMPLE=</xsd:appinfo><xsd:appinfo>USEHEADER=false</xsd:appinfo></xsd:annotation>
</xsd:schema>